### ISSUE TITLE
ApiTests non-deterministically fail on Ubuntu

### ISSUE THREAD

**Issue by dvoits** [itislab/alpheus#49]
See failed tests in the following build:

https://travis-ci.org/itislab/alpheus/builds/587449940?utm_source=github_status&utm_medium=notification

**Comment by dvoits** [comment]
See also 
https://travis-ci.org/itislab/alpheus/builds/587572517?utm_source=github_status&utm_medium=notification

**Comment by dgrechka** [comment]
The failing tests are resolved by PR #53 . But the reason for the failures are not determined.
Thus, leaving this bug open.

**Comment by dgrechka** [comment]
Test triggering the issue is disabled in a865b45

**Comment by dgrechka** [comment]
Considering this one as fixed by the PR #64
